#!/bin/sh

set -e

echo "Removing highlight handlers from defaults.list"
sed -i -e '/x-maemo-highlight\/porntrex-video-url=cutetube2.desktop\x-maemo-highlight/d' /usr/share/applications/defaults.list

#DEBHELPER#

# Make sure the uninstallation is always considered successful
exit 0
